Homework5
kordonskanastya/ma-nodeJS pull request #6
Opened 2021-12-17 14:14 UTC by kordonskanastya

2021-12-20 11:04 UTC, b-des requested changes

2021-12-20 11:04 UTC, b-des commented on src/config/index.js
> +  loginEnv: process.env.LOGIN || process.exit(1),
Потрібно викидати помилку якщо значення відсутнє. Можна створити функцію, де буде виводитись помилка та завершуватись процес(якщо без цеї енви неможлива подальша робота програми).

2021-12-20 11:04 UTC, b-des commented on src/server/index.js
> +const start = () => listener;
Сервер запуститься навіть якщо ти ніде не викличеш функцію start. Ти запускаєш сервер відразу ж коли виконається строка 6. Якщо ти хоч запустити listener при виклику функції start, тобі потрібно переробити це

2021-12-20 11:04 UTC, b-des commented on src/server/middlewares/index.js
> +  const auth = { login: loginEnv, password: passwordEnv };
Немає сенсу створювати новий об'єкт щоб просто виконати перевірку
`login === auth.login && password === auth.password`, можна простіше зробити:
`login === loginEnv && password === passwordEnv`

2021-12-20 11:04 UTC, b-des commented on src/server/middlewares/index.js
> +  const b64auth = (req.headers.authorization || '').split(' ')[1] || '';
Зроби конструкцію простішою. Також ти не перевіряюш header, наприклад я можу виконати запит так:
![image](https://user-images.githubusercontent.com/14833882/146749316-5b0eaa69-8d6e-4586-bb3d-677a0c3458f0.png)
Тобто додай перевірку для типу авторизації

2021-12-20 11:04 UTC, b-des commented on src/server/middlewares/index.js
> +    next(new Error('Not Authorized'));
Задумка хороша, але... в даному випадку ми попадем у errorHandler, де ти робиш перевірку і використовуюєш для цього текст помилки, тобто в тебе логіка дуже прив'язана саме на тексті і якщо змінити текст тут, то і в errorHandler треба змінювати, що не зручно. Краще тут відправляти зразу результат. Також зверни увагу що статус код для unauthorized = 401

2021-12-20 11:04 UTC, b-des commented on src/server/middlewares/index.js
> +  const errorStr = err.toString();
Чому toString? В такому випадку ми отримаєм такий результат
 _"error": "Error: Not Authorized"_ 
 Використай властивість err.message і отримаєм більш логічну відповідь:
  _"error": "Not Authorized"_

2021-12-20 11:04 UTC, b-des commented on src/server/routes/discount.js
> +discount.get('/promise', (req, res) => {
Коли викликаєм функцію контролера, можна спростити і не викликати саму функцію, а передавати її як аргумент у функцію роутинга, якщо співпадають параметри, а вони в даному випадку співпадають. Переписавши отримаєм:
`discount.get('/promise', controllers.getArrayWithDiscountPromise);`
Далі функція getArrayWithDiscountPromise виконається із передачею параметрів req, res.
Це стосується всіх роутів

2021-12-20 11:04 UTC, b-des commented on src/server/routes/index.js
> +  if (req.headers['content-type'] === 'text/csv') {
Краще вже умову перенести у функцію uploadCsv, щоб тримати файл з роутами consistent(послідовний)

2021-12-20 11:04 UTC, b-des commented on src/server/routes/index.js
> +app.use(bodyParser.json());
Згрупуй усі middlewares, бо в тебе то спочатку `app.use(authorization);` потім `app.put('/data') `, тоді знову app.use...

2021-12-20 11:04 UTC, b-des commented on src/server/routes/index.js
> +app.use(errorHandler);
Згрупуй усі middlewares, краще їх записувати перед роутами

2021-12-20 11:04 UTC, b-des commented on src/server/middlewares/index.js
> +    next(new Error('Not Authorized'));
Хоча в ДЗ написано повертати 403, рекомендую використати 401

2021-12-21 08:04 UTC, kordonskanastya commented on src/server/routes/index.js
> +app.use(errorHandler);
якщо я перенесу цю middleware перед роутами то в мене завжди буде Page not found

2021-12-21 11:01 UTC, merged